import axios from "axios";
import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  const summonerName = "가장따뜻한색블루";

  async function getData() {
    const response = await axios.get(
      `https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/${summonerName}?api_key=`
    );

    console.log(response);
  }

  useEffect(() => {
    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
