import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import styled from "styled-components";

export default function Home() {
  const [summonerName, setSummonerName] = useState();
  const router = useRouter();

  const goToSummonerInfomation = () => {
    router.push({
      pathname: `/entries/${summonerName}`,
    });
  };
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        onChange={(e) => {
          setSummonerName(e.target.value);
        }}
      />
      <button onClick={goToSummonerInfomation}>검색</button>
    </Container>
  );
}

const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
`;
